### ISSUE TITLE
Renderer wrapper should use role="application" so that keyboard shortcuts will work for screen reader users

### ISSUE THREAD

**Issue by majornista** [cmudig/data-navigator#34]
At:

https://github.com/cmudig/data-navigator/blob/d484691ac9de81865f8e5ca16d445134b1f7526f/src/rendering.ts#L49-L51

Use `role="application"` on the renderer wrapper element so that screen reader software on Windows will shift into forms mode and keyboard interactions will work.

**Comment by frankelavsky** [comment]
10/10 for finding this because I actually thought that it had this role already. Apparently, the wrapper never got a role! Easy, easy fix on this (and it should have had this anyway since I was basing it off the pattern we first put together at Visa for VCC).

**Comment by frankelavsky** [comment]
Resolved in [v1.1.0](https://github.com/cmudig/data-navigator/releases/tag/v1.1.0).
