### ISSUE TITLE
Node that receives focus should have tabindex="0" so that one can tab away and back to the data navigator

### ISSUE THREAD

**Issue by majornista** [cmudig/data-navigator#35]
At:

https://github.com/cmudig/data-navigator/blob/d484691ac9de81865f8e5ca16d445134b1f7526f/src/rendering.ts#L151

The node that receives focus within the data navigator currently has `[tabindex="-1"]`, which means that should the user tab away from the data navigator, they can't shift+tab back to the focused node in the data navigator.

Use `[tabindex="0"]`, so that the node that receives focus within the data navigator will be included in the tab navigation order for the web page.

**Comment by frankelavsky** [comment]
Oh yeah, this is a great find and an easy fix! When I get a free moment, I'll change this over.

**Comment by frankelavsky** [comment]
Resolved in [v1.1.0](https://github.com/cmudig/data-navigator/releases/tag/v1.1.0).
